"""Runtime-only RMAP v1.0.2 integration; pending sessions use one worker.

Keys are supplied by the operator, never generated by the application.
The lock covers protocol state and publication so a replay cannot publish twice.
"""
from pathlib import Path
from threading import RLock
import time

from rmap import RMAPServer
from rmap.crypto import decrypt_json


class InvalidRMAPMessage(ValueError):
    pass


class RMAPService:
    SESSION_TTL = 300

    def __init__(self, config):
        self.document_id = int(config["RMAP_DOCUMENT_ID"])
        if self.document_id <= 0:
            raise ValueError("Invalid assigned document")
        self.server = RMAPServer(
            server_public_key_path=config["RMAP_SERVER_PUBLIC_KEY_PATH"],
            server_private_key_path=config["RMAP_SERVER_PRIVATE_KEY_PATH"],
            passphrase=config.get("RMAP_SERVER_KEY_PASSPHRASE") or None,
            linkPrefix="",
        )
        public = self.server.serverPublicKey
        private = self.server.serverPrivateKey
        if not public.is_public or private.is_public or public.fingerprint != private.fingerprint:
            raise ValueError("Invalid server keypair")
        self.passphrase = config.get("RMAP_SERVER_KEY_PASSPHRASE") or None
        if private.is_protected:
            if not self.passphrase:
                raise ValueError("Missing server key passphrase")
            with private.unlock(self.passphrase):
                pass
        directory = Path(config["RMAP_CLIENT_KEYS_DIR"])
        if not directory.is_dir():
            raise ValueError("Missing client keys directory")
        for path in sorted(directory.glob("*.asc")):
            if path.is_file():
                self.server.loadIdentity(path.stem, path)
                if not self.server.identities[path.stem].publicKey.is_public:
                    raise ValueError("Client identities require public keys")
        if not self.server.identities:
            raise ValueError("No client public keys")
        self._expires = {}
        self._lock = RLock()

    def _forget(self, identity):
        info = self.server.identities[identity]
        # v1.0.2 does not consume sessions. Keep its nonce index in sync.
        if self.server._nonce_server_index.get(info.nonceServer) == identity:
            self.server._nonce_server_index.pop(info.nonceServer, None)
        info.nonceClient = info.nonceServer = None
        self._expires.pop(identity, None)

    def _expire(self):
        now = time.monotonic()
        for identity, deadline in list(self._expires.items()):
            if deadline <= now:
                self._forget(identity)

    def _validate(self, message, nonce_field):
        # Validate plaintext before receiveMsg1 can mutate library state.
        # The library still performs the actual handshake and encryption.
        data = decrypt_json(message, self.server.serverPrivateKey, self.passphrase)
        nonce = data.get(nonce_field)
        if type(nonce) is not int or not 0 <= nonce < 2**64:
            raise InvalidRMAPMessage("Invalid nonce")
        return data

    def initiate(self, message):
        with self._lock:
            self._expire()
            data = self._validate(message, "nonceClient")
            identity = data.get("identity")
            if not isinstance(identity, str) or identity not in self.server.identities:
                raise InvalidRMAPMessage("Unknown identity")
            self._forget(identity)
            previous_index = dict(self.server._nonce_server_index)
            try:
                _, response = self.server.receiveMsg1(message)
                nonce = self.server.identities[identity].nonceServer
                if nonce in previous_index:
                    raise InvalidRMAPMessage("Nonce collision")
            except Exception:
                self._forget(identity)
                self.server._nonce_server_index.update(previous_index)
                raise
            self._expires[identity] = time.monotonic() + self.SESSION_TTL
            return response

    def get_link(self, message, publish):
        with self._lock:
            self._expire()
            self._validate(message, "nonceServer")
            identity, link, response = self.server.receiveMsg2(message)
            # Preparing ciphertext is not publication: return it only after
            # the PDF is written and the Versions transaction has committed.
            publish(self.document_id, identity, link)
            self._forget(identity)
            return response
